#!/bin/zsh
set +euo pipefail
command -v brew &>/dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
command -v mise &>/dev/null || brew install mise
source ~/.zshrc
! type mise | grep -q 'mise ()' && echo 'eval "$(mise activate zsh)"' >> "${ZDOTDIR-$HOME}/.zshrc"
source ~/.zshrc
mise trust
mise install
echo "Setup complete."
