#!/bin/bash
set -euo pipefail

source "$(dirname "$0")/.init"

precondition "which pkgx" "1"

section "Invoke the script"
expect -d <<EOF
set timeout 60
spawn /bin/bash -c  $(cmd_for_setup_environment)
expect "Install pkgx?"
send -- "n\r"
expect eof
EOF

#section "Asserts"
#precondition "which pkgx" "0"
