#!/usr/bin/env -S pkgx +pip@24 python@3

import os
import subprocess
import sys

try:
    import pexpect
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pexpect"])
    import pexpect

BIN_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../bin'))
PROMPT = '$ '

child = pexpect.spawn("/bin/zsh -f", env={
    "PS1": PROMPT,
    "fake_should_install_pkgx": "0",
    "fake_install_pkgx": "0"
}, timeout=5)
child.logfile = sys.stdout.buffer
try:
    child.expect_exact(PROMPT)

    child.sendline(f"source {BIN_DIR}/setup-environment.sh")
    child.expect_exact("Ok to proceed?")
    child.sendline("y")
    child.expect_exact("Install pkgx?")
    child.sendline("y")

    child.expect_exact(PROMPT)
    child.sendline("exit")
    child.expect(pexpect.EOF)
except (pexpect.exceptions.TIMEOUT, pexpect.exceptions.EOF) as e:
    print(str(e))
    child.close(force=True)
else:
    child.close()
sys.exit(child.exitstatus)
