#!/usr/bin/env -S pkgx +pip@24 +zsh@5 +bash@5 python@3
import sys
import os

parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from test_runner import run_tests_against_shells


def test(child, prefix, bin_dir, prompt):
    child.sendline("export fake_should_install_pkgx=1 fake_should_integrate_pkgx=1 fake_should_clone_repo=1 fake_should_activate_dev=0")
    child.expect_exact(prompt)
    child.sendline(f"source {bin_dir}/bootstrap")
    child.expect_exact("Ok to proceed?")
    child.sendline("y")
    child.expect("pkgx is installed")
    child.expect("Shell integration is active")
    child.expect("Repository is available")
    child.expect("Development environment not active")
    child.expect("User action required: Activate developer environment")
    child.expect_exact(prompt)


if __name__ == "__main__":
    run_tests_against_shells(test)
