#!/usr/bin/env -S pkgx +pip@24 +zsh@5 +bash@5 python@3
import sys
import os

parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from test_runner import run_tests_against_shells

ASCII_BULLET = 'M-bM-^@M-"'
DOWNWARDS_ARROW_WITH_TIP_RIGHTWARDS = '^[[2mM-bM-^FM-3'

def test(child, prefix, bin_dir, prompt):
    child.sendline(f"source {bin_dir}/.shhelpers")
    child.expect_exact(prompt)

    expect_color = lambda command, expect: expect_color_codes(child, command, expect, prompt)

    expect_color('p; step "Step" "echo simple; true"',
                 [f'{prefix} {ASCII_BULLET} Step^[[0m^[[92m^[[1m M-bM-^\M-^S^[[0m'])

    expect_color('p; DEBUG=true step "Step" "echo simple-debug; true"',
                 [
                     f'{prefix} {ASCII_BULLET} Step^[[0m^[[92m^[[1m M-bM-^\M-^S^[[0m',
                     '^[[2mDEBUG: ^[[0m> Executed: echo simple-debug; true^[[0m',
                     '^[[2mDEBUG: ^[[0msimple-debug^[[0m'
                 ])

    expect_color('p; step "Step" "echo fails; false"',
                 [
                     f'{prefix} {ASCII_BULLET} Step^[[0m^[[91m^[[1m x^[[0m',
                     '^[[31m> Executed: ^[[0m^[[31m^[[1mecho fails; false^[[0m',
                     '^[[31mfails^[[0m'
                 ])

    expect_color('p; DEBUG=true step "Step" "echo fails-debug; false"',
                 [
                     f'>> {ASCII_BULLET} Step^[[0m^[[91m^[[1m x^[[0m',
                     '^[[31m> Executed: ^[[0m^[[31m^[[1mecho fails-debug; false^[[0m',
                     '^[[31mfails-debug^[[0m',
                     '^[[2mDEBUG: ^[[0mDone with \'Step\', exited 1^[[0m'
                 ])

    expect_color('p; step --with-output "Step" "echo with-output; true"',
                 [
                     f'>> {ASCII_BULLET} Step:^[[0m',
                     'with-output',
                     f'{DOWNWARDS_ARROW_WITH_TIP_RIGHTWARDS} Step^[[0m^[[92m^[[1m M-bM-^\M-^S^[[0m'
                 ])

    expect_color('p; DEBUG=true step --with-output "Step" "echo with-output-debug; true"',
                 [
                     f'>> {ASCII_BULLET} Step:^[[0m',
                     'with-output-debug',
                     f'{DOWNWARDS_ARROW_WITH_TIP_RIGHTWARDS} Step^[[0m^[[92m^[[1m M-bM-^\M-^S^[[0m',
                     '^[[2mDEBUG: ^[[0m> Executed: echo with-output-debug; true^[[0m',
                 ])

    expect_color('p; step --with-output "Step" "echo fails-with-output; false"',
                 [
                     f'>> {ASCII_BULLET} Step:^[[0m',
                     'fails-with-output',
                     f'{DOWNWARDS_ARROW_WITH_TIP_RIGHTWARDS} Step^[[0m^[[91m^[[1m x^[[0m',
                     '^[[31m> Executed: ^[[0m^[[31m^[[1mecho fails-with-output; false^[[0m',
                 ])

    expect_color('p; DEBUG=true step --with-output "Step" "echo fails-with-output-debug; false"',
                 [
                     f'>> {ASCII_BULLET} Step:^[[0m',
                     'fails-with-output-debug',
                     f'{DOWNWARDS_ARROW_WITH_TIP_RIGHTWARDS} Step^[[0m^[[91m^[[1m x^[[0m',
                     '^[[31m> Executed: ^[[0m^[[31m^[[1mecho fails-with-output-debug; false^[[0m',
                     '^[[2mDEBUG: ^[[0mDone with \'Step\', exited 1^[[0m',
                 ])


def expect_color_codes(child, command, expect_exacts, prompt):
    """
    Execute command directly, and then again piped through 'cat -v' with FORCE_COLOR=true
    to show color codes and assert the literal color codes against expected.
    """
    child.sendline(f'({command}); true', )
    child.expect_exact(prompt)
    child.sendline(f'FORCE_COLOR=true; ({command}) | cat -v; true')
    for expect_exact in expect_exacts:
        child.expect_exact(expect_exact)
    child.expect_exact(prompt)


if __name__ == "__main__":
    run_tests_against_shells(test)
