#!/usr/bin/env -S pkgx +pip@24 +zsh@5 +bash@5 python@3
import sys
import os

parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from test_runner import run_tests_against_shells


def test(child, prefix, bin_dir, prompt):
    child.sendline(f"source {bin_dir}/.shhelpers")
    child.expect_exact(prompt)

    child.sendline('p; echo "#$(_pad "ham" 10)#"')
    child.expect_exact(f"{prefix} #ham       #")
    child.sendline('p; echo "#$(_pad "bacon" 10)#"')
    child.expect_exact(f"{prefix} #bacon     #")
    child.sendline('p; echo "#$(_leftpad "ham" 10)#"')
    child.expect_exact(f"{prefix} #       ham#")
    child.sendline('p; echo "#$(_leftpad "bacon" 10)#"')
    child.expect_exact(f"{prefix} #     bacon#")
    child.expect_exact(prompt)


if __name__ == "__main__":
    run_tests_against_shells(test)
