#!/bin/bash
set -e

echo -n "Output contains: \"$1\"… "
if grep -q "$1" ~/output.txt; then
  echo -e "\033[0;32m✔\033[0m"
  exit_status=0
else
  echo -e "\033[0;31m✘\033[0m"
  exit_status=1
fi

echo "::group::(Output)"
cat ~/output.txt
echo "::endgroup::"

exit $exit_status
