name: ci

on:
  push:
    branches: [ "**" ] # this triggers only on branch commits, which prevents triggering off of tag-only commits
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

env:
  scenarios-dir: test/scenarios

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.scenarios.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: | 
            ${{ env.scenarios-dir }}

      - id: scenarios
        run: |
          scenarios=$(ls ${{ env.scenarios-dir }} | jq -Rsc 'split("\n")[:-1]')
          echo "scenarios=$scenarios"
          echo "scenarios=$scenarios" >> $GITHUB_OUTPUT

  scenario:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-13 ]
        scenario: ${{ fromJson(needs.prepare.outputs.scenarios) }}
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.scenario }} (on ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/dev@v0
      - name: Run test
        run: |
          ./${{ env.scenarios-dir }}/${{ matrix.scenario }}
