name: e2e

on:
  push:
    branches: [ "**" ] # this triggers only on branch commits, which prevents triggering off of tag-only commits
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-e2e

env:
  E2E_URL: https://raw.githubusercontent.com/gaggle/perfect-elixir/perfect-elixir-3-development-workflows-%26-processes/bin/setup-environment.sh
  NONINTERACTIVE: true

jobs:
  zsh:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-13 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Pre-installation check
        run: >
          zsh -l -c '
          if command -v pkgx; then 
            echo "pkgx already installed"; exit 1; 
          fi
          '
      - name: Installation
        run: >
          zsh -l -c '
          curl -fsSL $E2E_URL > /tmp/setup.sh && source /tmp/setup.sh; rm /tmp/setup.sh;
          if ! command -v pkgx; then
            echo "pkgx is not available after installation"; exit 1;
          fi
          '
      - name: Post-installation check
        run: >
          zsh -l -c '
          if ! command -v pkgx; then
            echo "pkgx not globally available"; exit 1;
          fi
          '
