name: e2e

on:
  push:
    branches: [ "**" ] # this triggers only on branch commits, which prevents triggering off of tag-only commits
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-e2e

env:
  E2E_URL: https://raw.githubusercontent.com/gaggle/perfect-elixir/perfect-elixir-3-development-workflows-%26-processes/bin/bootstrap
  NONINTERACTIVE: true

jobs:
  zsh:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-13 ]
    runs-on: ${{ matrix.os }}
    name: zsh (${{ matrix.os }})
    steps:
      - run: >
          zsh -l -c '
          set -e;
          
          curl -fsSL $E2E_URL > /tmp/setup.sh && source /tmp/setup.sh > 1_should_install_pkgx.txt;
          echo ::group::cat 1_should_install_pkgx.txt;
          cat 1_should_install_pkgx.txt;
          echo ::endgroup::;
          grep -q "User action required: Install pkgx" 1_should_install_pkgx.txt;
          
          echo ::group::brew install pkgxdev/made/pkgx;
          brew install pkgxdev/made/pkgx;
          echo ::endgroup::;

          source /tmp/setup.sh > 2_should_integrate_pkgx.txt;
          echo ::group::cat 2_should_integrate_pkgx.txt;
          cat 2_should_integrate_pkgx.txt;
          echo ::endgroup::;
          grep -q "User action required: Activate pkgx shell integration" 2_should_integrate_pkgx.txt;
          
          echo ::group::pkgx integrate;
          eval "$(pkgx integrate)";
          echo ::endgroup::;

          source /tmp/setup.sh > 3_should_clone_repo.txt;
          echo ::group::cat 3_should_clone_repo.txt;
          cat 3_should_clone_repo.txt;
          echo ::endgroup::;
          grep -q "User action required: Clone gaggle/perfect-elixir repository" 3_should_clone_repo.txt;

          echo ::group::git clone git@github.com:gaggle/perfect-elixir.git;
          git clone https://github.com/gaggle/perfect-elixir.git;
          cd perfect-elixir;
          git checkout "perfect-elixir-3-development-workflows-&-processes";
          echo ::endgroup::;

          source /tmp/setup.sh > 4_should_activate_dev.txt;
          echo ::group::cat 4_should_activate_dev.txt;
          cat 4_should_activate_dev.txt;
          echo ::endgroup::;
          grep -q "User action required: Activate developer environment" 4_should_activate_dev.txt;

          echo ::group::dev;
          dev;
          echo ::endgroup::;

          source /tmp/setup.sh > 5_good_to_go.txt;
          echo ::group::cat 5_good_to_go.txt;
          cat 5_good_to_go.txt;
          echo ::endgroup::;
          grep -q "Good to go" 5_good_to_go.txt;
          '
