name: e2e

on:
  push:
    branches: [ "**" ] # this triggers only on branch commits, which prevents triggering off of tag-only commits
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-e2e

env:
  E2E_URL: https://raw.githubusercontent.com/gaggle/perfect-elixir/perfect-elixir-3-development-workflows-%26-processes/bin/bootstrap
  NONINTERACTIVE: true

jobs:
  ok-from-scratch:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-13 ]
    runs-on: ${{ matrix.os }}
    name: ok-from-scratch (${{ matrix.os }})
    steps:
      - run: >
          zsh -l -c '
          curl -fsSL $E2E_URL > /tmp/setup.sh && source /tmp/setup.sh > output.txt;
          cat output.txt;
          grep -q "User action required: Install pkgx" output.txt && exit 0 || exit 1;
          '
